# Generated by Django 2.2.3 on 2020-10-19 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='facultad',
        ),
    ]
