# Generated by Django 2.2.3 on 2020-10-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_customuser_facultad'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_decano',
            field=models.BooleanField(default=False),
        ),
    ]
