# Generated by Django 2.2.3 on 2020-10-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_customuser_is_decano'),
    ]

    operations = [
        migrations.AddField(
            model_name='folio',
            name='priority_one',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folio',
            name='priority_two',
            field=models.BooleanField(default=False),
        ),
    ]
