# Generated by Django 2.2.3 on 2020-11-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20201103_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['carrera']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_director',
            field=models.BooleanField(default=False),
        ),
    ]
