# Generated by Django 2.2.3 on 2020-11-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20201109_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_director',
            new_name='is_manager',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_log',
            field=models.BooleanField(default=False),
        ),
    ]
